apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-service-deployment
  labels:
    app: sales-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sales-service
  template:
    metadata:
      labels:
        app: sales-service
    spec:
      containers:
        - name: sales-service
          image: grz3lak1997/sales-service:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: sales-service-service
  labels:
    app: sales-service
spec:
  selector:
    app: sales-service
  ports:
    - protocol: TCP
      name: http-traffic
      port: 8080
      targetPort: 8080


---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sales-service-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: sales-service
  endpoints:
    - port: http-traffic
      path: "/actuator/prometheus"
      interval: 10s
