{
 "title": "Shop App",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Mailing Service Total Number of Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "total_mailing_service_request_total"
    }
   ]
  },
  {
   "title": "Mailing Service Request Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(total_mailing_service_request_total[15m])"
    }
   ]
  },
  {
   "title": "Mailing Service Log File Free Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "log_file_size_mailing_service" }
   ]
  }
 ]
}