

apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoes-service-deployment
  labels:
    app: {{ .Values.applications.deployment.shoes }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.applications.deployment.shoes }}
  template:
    metadata:
      labels:
        app: {{ .Values.applications.deployment.shoes }}
    spec:
      containers:
        - name: {{ .Values.applications.deployment.shoes }}
          image: {{ .Values.applications.image.shoes }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env: # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: db-conf  # name of configMap
                  key: host
            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: name
            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: db-credentials # Secret Name
                  key: username
            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password


---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applications.services.shoes }}
  labels:
    app: {{ .Values.applications.deployment.shoes }}
spec:
  selector:
    app: {{ .Values.applications.deployment.shoes }}
  ports:
    - protocol: TCP
      name: http-traffic
      port: 8080
      targetPort: 8080

