apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.applications.name.books }}
  labels:
    app: {{ .Values.applications.deployment.books }}
spec:
  replicas: {{ .Values.applications.replicas.books }}
  selector:
    matchLabels:
      app: {{ .Values.applications.deployment.books }}
  template:
    metadata:
      labels:
        app: {{ .Values.applications.deployment.books }}
    spec:
      containers:
        - name: {{ .Values.applications.deployment.books }}
          image: {{ .Values.applications.image.books }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.applications.port.books }}
          env: # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: db-conf  # name of configMap
                  key: host
            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: name
            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: db-credentials # Secret Name
                  key: username
            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applications.services.books }}
  labels:
    app: {{ .Values.applications.deployment.books }}
spec:
  selector:
    app: {{ .Values.applications.deployment.books }}
  ports:
    - protocol: TCP
      name: http-traffic
      port: 8080
      targetPort: 8080

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.applications.prometheus.monitor.books }}
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{ .Values.applications.deployment.books }}
  endpoints:
    - port: http-traffic
      path: "/actuator/prometheus"
      interval: 10s
